name: get-tag
description: create the correct upstream image name and export
inputs:
  pg-version:
    description: postgres version
    required: true
  base-image:
    description: postgres base image
    required: true
outputs:
  tag:
    description: postgres image tag
    value: ${{ steps.image-tag.outputs.tag }}
runs:
  using: composite
  steps:
    - id: image-tag
      run: |
        version="${VERSION}"
        baseimage="${BASE_IMAGE}"
        if [ ${baseimage} == "alpine" ]; then
            if [ ${version} == "latest" ]; then
                echo "::set-output name=tag::alpine"
            else
                echo "::set-output name=tag::${version}-alpine"
            fi
        else
          echo "::set-output name=tag::${version}"
        fi
      env:
        PG_VERSION: ${{ inputs.pg-version }}
        BASE_IMAGE: ${{ inputs.base-image }}
      shell: bash


