name: Main

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  build:
    strategy:
      matrix:
        pg-version: [ '9.5', '9.6', '10', '11', '12', '13', 'latest' ]
        pg-base-image: [ 'alpine', 'debian' ]
        pgtap-version: [ '1.1.0' ]
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/get-tag
        id: get-tag
        with:
          pg-version: ${{ matrix.pg-version }}
          base-image: ${{ matrix.pg-base-image }}
      - name: docker build
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker build \
            --build-arg POSTGRES_VERSION=${{ steps.get-tag.outputs.tag }} \
            --build-arg PGTAP_VERSION=${{ matrix.pgtap-version }} \
            --tag ${{ steps.get-tag.outputs.tag }}-${{ matrix.pgtap-version }} \
            --file ${{ matrix.pg-base-image }}.Dockerfile \
            .

